# Site settings
# Enter your own credentials here
title: "Structure Property Relationships for a Polymer/Fiber Composite System"
email: awhite40@gatech.edu
description: >
  Developing structure property linkages for glass fiber reinforced polymer systems.
baseurl: "/MIC-Modeling-Polymer-Composites" # replace ``/research-pages`` with the name of the parents repository
url: "awhite40.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
#twitter_username: twitterhandle
disqus: awhite40

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: awhite40
  repo: research-pages
  # Branch hosting Github pages
  branch: gh-pages
